
[sources.33]
aka = ["sleele的博客"]
url = "https://sleele.com/feed/"
enabled = false

[sources.36]
aka = ["云原生实验室"]
url = "https://fuckcloudnative.io/index.xml"

[sources.39]
aka = ["吴良超的学习笔记"]
url = "http://wulc.me/atom.xml"

[sources.40]
aka = ["四火的唠叨"]
url = "https://www.raychase.net/feed"
enabled = false

[sources.42]
aka = ["国光"]
url = "https://www.sqlsec.com/atom.xml"
enabled = false

[sources.43]
aka = ["土豆不好吃"]
url = "https://dmesg.app/feed"

[sources.44]
aka = ["宇宙的心弦"]
url = "https://www.physixfan.com/feed/"

[sources.45]
aka = ["寒雁"]
url = "https://kiwenlau.com/atom.xml"
enabled = false


[sources.51]
aka = ["王子亭的博客"]
url = "https://jysperm.me/atom.xml"

[sources.52]
aka = ["生产力维基"]
url = "https://productivity.wiki/feed/podcast"

[sources.54]
aka = ["约伊兹的萌狼乡手札"]
url = "https://blog.yoitsu.moe/feeds/all.atom.xml"



[sources.58]
aka = ["茶歇驿站 - Gopher, OpenSource Fans, 成长之路有我相伴。"]
url = "https://maiyang.me/index.xml"

[sources.59]
aka = ["酷 壳 – CoolShell"]
url = "http://coolshell.cn/feed"

[sources.60]
aka = ["高策"]
url = "http://gaocegege.com/Blog/rss.xml"

[sources.61]
aka = ["Fastly Blog"]
url = "https://www.fastly.com/blog_rss.xml"
enabled = false


[sources.64]
aka = ["The Python Data & Science Podcast.__init__"]
url = "https://www.podcastinit.com/feed/mp3/"

[sources.65]
aka = ["Think Fast, Talk Smart: Communication Techniques."]
url = "https://rss.art19.com/think-fast-talk-smart"


[sources.75]
aka = ["Twitter - @breathing_funny"]
url = "https://twitter2rss.nomadic.name/breathing_funny"
group = "twitter"

[sources.76]
aka = ["Twitter - @jamella_hoshino"]
url = "https://twitter2rss.nomadic.name/jamella_hoshino"
group = "twitter"
