
[sources."nyonyoko5871"]
url = "http://nuc.local:1200/twitter/media/nyonyoko5871"
group = "twitter"

[sources."Megumi_Nange"]
url = "http://nuc.local:1200/twitter/media/Megumi_Nange"
group = "twitter"

[sources."trufflemilky"]
url = "http://nuc.local:1200/twitter/media/trufflemilky"
group = "twitter"

[sources."niyeye2019"]
url = "http://nuc.local:1200/twitter/media/niyeye2019"
group = "twitter"

[sources."Aoiiii_26"]
url = "http://nuc.local:1200/twitter/media/Aoiiii_26"
group = "twitter"

[sources."Xansoon"]
url = "http://nuc.local:1200/twitter/media/Xansoon"
group = "twitter"

[sources."yummychiyo"]
url = "http://nuc.local:1200/twitter/media/yummychiyo"
group = "twitter"


[sources."paulgraham"]
url = "http://www.aaronsw.com/2002/feeds/pgessays.rss"



[sources."scotthyoung"]
url = "https://www.scotthyoung.com/feed/"
enabled = false

[sources."andrewchen"]
url = "https://andrewchen.com/feed/"

[sources."Of Dollars And Data"]
url = "https://ofdollarsanddata.com/feed/"

[sources."markmanson"]
url = "https://markmanson.net/feed"

[sources."fs.blog"]
url = "https://fs.blog/feed/"

[sources."seths.blog"]
url = "https://seths.blog/feed/"

[sources."jamesclear"]
url = "https://jamesclear.com/feed"

[sources."dariusforoux"]
url = "https://dariusforoux.com/feed/"

[sources."Break up the wrong tree"]
url = "https://bakadesuyo.com/feed/"

[sources."joelonsoftware"]
url = "https://www.joelonsoftware.com/feed/"


[sources."themarginalian"]
url = "https://feedproxy.google.com/brainpickings/rss"

[sources."collaborativefund"]
url = "http://feeds.feedburner.com/collabfund"

[sources."rioko041120"]
url = "http://nuc.local:1200/twitter/media/rioko041120"
group = "twitter"

[sources."smilecutty"]
url = "http://nuc.local:1200/twitter/media/smilecutty"
group = "twitter"

[sources."NinJA_Azz"]
url = "http://nuc.local:1200/twitter/media/NinJA_Azz"
group = "twitter"



[sources."Bossy_0618"]
url = "http://nuc.local:1200/twitter/media/Bossy_0618"
group = "twitter"

[sources."sirotama0907"]
url = "http://nuc.local:1200/twitter/media/sirotama0907"
group = "twitter"


[sources."GavinYa13805005"]
url = "http://nuc.local:1200/twitter/media/GavinYa13805005"
group = "twitter"


[sources."sama31598328"]
url = "http://nuc.local:1200/twitter/media/sama31598328"
group = "twitter"

[sources."Takomayuyi"]
url = "http://nuc.local:1200/twitter/media/Takomayuyi"
group = "twitter"



[sources."aqua_cosplay"]
url = "http://nuc.local:1200/twitter/media/aqua_cosplay"
group = "twitter"


[sources."abaoyeshitunia1"]
url = "http://nuc.local:1200/twitter/media/abaoyeshitunia1"
group = "twitter"

[sources."softwareengineeringdaily"]
url = "https://softwareengineeringdaily.com/feed/podcast/"

[sources."ShipIt"]
url = "https://changelog.com/shipit/feed"

[sources."DevOps and Docker Talk"]
url = "https://feeds.transistor.fm/devops-and-docker-talk"
enabled = false

[sources."自古多情伤离别 -AcFun弹幕视频网"]
url = "http://nuc.local:1200/acfun/user/video/1378895"

[sources."小约翰可汗"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCAeIZxbLS06qOpBTAGT1qxA"

[sources."马卡耶夫造飞机"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCoXkotCJ_wAk7HSY5bwJnAQ"



[sources.3]
aka = ["Hi, DIYgod"]
url = "https://diygod.me/atom.xml"

[sources.4]
aka = ["Hwchiu Learning Note"]
url = "https://www.hwchiu.com/atom.xml"


[sources.6]
aka = ["Lindsay Hill"]
url = "https://lkhill.com/feed/index.xml"



[sources.9]
aka = ["Martin Fowler"]
url = "https://martinfowler.com/feed.atom"

[sources.10]
aka = ["Nolla"]
url = "https://cmgs.me/feed.xml"

[sources.11]
aka = ["Posts on Nova Kwok's Awesome Blog"]
url = "https://nova.moe/feed"

[sources.12]
aka = ["Retro Game Mechanics Explained"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCwRqWnW5ZkVaP_lZF7caZ-g"

[sources.13]
aka = ["Rss Feed - 苏洋博客"]
url = "https://soulteary.com/feed/"

[sources.14]
aka = ["Scateu Blog - S.B."]
url = "http://scateu.github.io/feed.xml"

[sources.15]
aka = ["Strange Parts"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCO8DQrSp5yEP937qNqTooOw"

[sources.16]
aka = ["Stratechery by Ben Thompson"]
url = "https://stratechery.com/feed/"

[sources.17]
aka = ["Summoning Salt"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCtUbO6rBht0daVIOGML3c8w"

[sources.18]
aka = ["TROOPERScon"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCPY5aUREHmbDO4PtR6AYLfQ"

[sources.19]
aka = ["TauCeti blog"]
url = "https://www.tauceti.blog/index.xml"
enabled = false

[sources.20]
aka = ["TeamNANOG"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCIvcN8QNgRGNW9osYLGsjQQ"

[sources.22]
aka = ["WonderWhy"]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCcEPmwpXKrKzZahqjwpIAsQ"

[sources.23]
aka = ["Zlatan Eevee"]
url = "https://ieevee.com/feed.xml"

[sources.24]
aka = ["codinghorror"]
url = "https://feeds.feedburner.com/codinghorror"

[sources.25]
aka = ["forecho 的独立博客"]
url = "https://blog.forecho.com/atom.xml"

[sources.26]
aka = ["iKoo's Dirty life"]
url = "https://feeds.feedburner.com/gythialy"

[sources.27]
aka = ["iTimothy"]
url = "https://xiaozhou.net/atom.xml"

[sources.28]
aka = ["ipSpace.net Blog Posts"]
url = "http://feed.ipspace.net/blog/"
enabled = false

[sources.29]
aka = ["lijiaocn.github.io"]
url = "https://www.lijiaocn.com/feed.xml"

[sources.30]
aka = ["manateelazycat.github.io"]
url = "https://manateelazycat.github.io/feed.xml"

[sources.31]
aka = ["rss.xml"]
url = "https://boz.com/rss.xml"

[sources.32]
aka = ["rule 11 reader"]
url = "http://rule11.tech/feed/"

[sources.33]
aka = ["sleele的博客"]
url = "https://sleele.com/feed/"
enabled = false

[sources.36]
aka = ["云原生实验室"]
url = "https://fuckcloudnative.io/index.xml"

[sources.39]
aka = ["吴良超的学习笔记"]
url = "http://wulc.me/atom.xml"

[sources.40]
aka = ["四火的唠叨"]
url = "https://www.raychase.net/feed"
enabled = false

[sources.42]
aka = ["国光"]
url = "https://www.sqlsec.com/atom.xml"
enabled = false

[sources.43]
aka = ["土豆不好吃"]
url = "https://dmesg.app/feed"

[sources.44]
aka = ["宇宙的心弦"]
url = "https://www.physixfan.com/feed/"

[sources.45]
aka = ["寒雁"]
url = "https://kiwenlau.com/atom.xml"
enabled = false

[sources.46]
aka = ["木子"]
url = "https://blog.k8s.li/atom.xml"

[sources.47]
aka = ["杜屹东的博客"]
url = "https://www.duyidong.com/atom.xml"

[sources.49]
aka = ["水晶命匣"]
url = "http://ghoulich.xninja.org/feed"


[sources.51]
aka = ["王子亭的博客"]
url = "https://jysperm.me/atom.xml"

[sources.52]
aka = ["生产力维基"]
url = "https://productivity.wiki/feed/podcast"

[sources.54]
aka = ["约伊兹的萌狼乡手札"]
url = "https://blog.yoitsu.moe/feeds/all.atom.xml"



[sources.58]
aka = ["茶歇驿站 - Gopher, OpenSource Fans, 成长之路有我相伴。"]
url = "https://maiyang.me/index.xml"

[sources.59]
aka = ["酷 壳 – CoolShell"]
url = "http://coolshell.cn/feed"

[sources.60]
aka = ["高策"]
url = "http://gaocegege.com/Blog/rss.xml"

[sources.61]
aka = ["Fastly Blog"]
url = "https://www.fastly.com/blog_rss.xml"
enabled = false


[sources.64]
aka = ["The Python Data & Science Podcast.__init__"]
url = "https://www.podcastinit.com/feed/mp3/"

[sources.65]
aka = ["Think Fast, Talk Smart: Communication Techniques."]
url = "https://rss.art19.com/think-fast-talk-smart"


[sources.75]
aka = ["Twitter - @breathing_funny"]
url = "https://twitter2rss.nomadic.name/breathing_funny"
group = "twitter"

[sources.76]
aka = ["Twitter - @jamella_hoshino"]
url = "https://twitter2rss.nomadic.name/jamella_hoshino"
group = "twitter"


[sources.81]
aka = ["无穷小亮的科普日常 的 bilibili 空间"]
url = "http://nuc.local:1200/bilibili/user/video/14804670"
group = "bilibili"

[sources.82]
aka = ["博物杂志 的 bilibili 空间"]
url = "http://nuc.local:1200/bilibili/user/video/50092850"
group = "bilibili"

